# Generated by Django 4.2.1 on 2023-05-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blog.post'),
        ),
    ]
