# Generated by Django 4.2.1 on 2023-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
