# Generated by Django 4.2.1 on 2023-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='password',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
