# Generated by Django 4.2.1 on 2023-05-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_password_comment_approved_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
