# Generated by Django 4.2.1 on 2023-05-28 05:51

import ckeditor.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2023, 5, 28, 5, 51, 1, 771710, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
